### ISSUE TITLE
Bug: Problem simulating/fitting with a parent particle with spin 0

### ISSUE THREAD

**Issue by Leongrim** [jiangyi15/tf-pwa#16]
I try to work on the suggestion of Wenbin and look into a decay only containing spin 0 particles (and compare the two tools).

I tried the decay chain D*(2300)0-> K+K- K0 with a(1450) and f(1370) as resonances.

Here is the config file I´m using: [config.txt](https://github.com/jiangyi15/tf-pwa/files/5780968/config.txt)

While loading the config following shows up:
```
integer division or modulo by zero D(0)*(2300)0->a(0)(1450)0+K~0 ()
integer division or modulo by zero D(0)*(2300)0->f(0)(1370)+K~0 ()
integer division or modulo by zero D(0)*(2300)0->a(0)(1450)++K- ()
integer division or modulo by zero D(0)*(2300)0->a(0)(1450)-+K+ ()
```` 
and while simularing following error occurs (using the tutorial file for this) :
```
Traceback (most recent call last):
  File "gen_toy.py", line 62, in <module>
    main()
  File "gen_toy.py", line 25, in main
    generate_toy_from_phspMC(
  File "gen_toy.py", line 50, in generate_toy_from_phspMC
    data = gen_data(
  File "/home/leonard/work/src/tf-pwa/tf_pwa/applications.py", line 255, in gen_data
    ampsq = amp(phsp)
  File "/home/leonard/work/src/tf-pwa/tf_pwa/amp/__init__.py", line 1704, in __call__
    ret = self.decay_group.sum_amp(data)
  File "/home/leonard/work/src/tf-pwa/tf_pwa/amp/__init__.py", line 1478, in sum_amp
    amp = self.get_amp(data)
  File "/home/leonard/work/src/tf-pwa/tf_pwa/amp/__init__.py", line 1410, in get_amp
    amp = decay_chain.get_amp(
  File "/home/leonard/work/src/tf-pwa/tf_pwa/amp/__init__.py", line 1195, in get_amp
    amp_d.append(i.get_amp(data_c[i], data_p, all_data=all_data))
  File "/home/leonard/work/src/tf-pwa/tf_pwa/amp/__init__.py", line 951, in get_amp
    H = self.get_helicity_amp(data, data_p, **kwargs)
  File "/home/leonard/work/src/tf-pwa/tf_pwa/amp/__init__.py", line 811, in get_helicity_amp
    m_dep = self.get_ls_amp(data, data_p, **kwargs)
  File "/home/leonard/work/src/tf-pwa/tf_pwa/amp/__init__.py", line 890, in get_ls_amp
    bf = self.get_barrier_factor2(
  File "/home/leonard/work/src/tf-pwa/tf_pwa/amp/__init__.py", line 934, in get_barrier_factor2
    ret = tf.concat(ret, axis=-1)
  File "/home/leonard/anaconda3/envs/tw/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/leonard/anaconda3/envs/tw/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 1654, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "/home/leonard/anaconda3/envs/tw/lib/python3.8/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1207, in concat_v2
    _ops.raise_from_not_ok_status(e, name)
  File "/home/leonard/anaconda3/envs/tw/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 6843, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: OpKernel 'ConcatV2' has constraint on attr 'T' not in NodeDef '[N=0, Tidx=DT_INT32]', KernelDef: 'op: "ConcatV2" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_UINT64 } } } host_memory_arg: "axis"' [Op:ConcatV2] name: concat
```

I hope you can help me and find the bug. 
The only thing I noticed is that this does not happen when I change the spin of the D(2300) to 1.

Thanks in advanced.

**Comment by jiangyi15** [comment]
We used LS coupling model to reduce parametersm. [see here](https://pwa.readthedocs.io/projects/tf-pwa/en/latest/api/tf_pwa.particle.html#tf_pwa.particle.GetA2BC_LS_list) ,so the process is not allowed. Here is a option ` p_break: True`(  "D(0)*(2300)0": [R_K+K-, K~0, p_break: True ] ), it can be used to allow parity violation.

**Comment by Leongrim** [comment]
Thanks you very much for the fast and helpful reply! It works now!
